import Head from 'next/head'
import { useState } from 'react'
import Footer from '../components/footer'
import Navbar from '../components/Navbar'
import ParticlesBG from '../components/Particles'
import Projects from '../components/Projects'
import PurpleButton from '../components/PurpleButton'
import styles from '../styles/home.module.scss'

export default function Home() {
    const dlCV = () => {
        const url = `${window.location.protocol + "//" + window.location.host}/cv/cv.pdf`
        const a = document.createElement("a")
        a.href = url
        a.download = url.split("/").pop()
        document.body.appendChild(a)
        a.click()
        document.body.removeChild(a)
    }

    const textIntroTemplate = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry.";

    const [textIntro, setTextIntro] = useState(textIntroTemplate.substring(0, 300))

    const seeMore = (val) => {
        if(val === "plus") {
            setTextIntro(textIntroTemplate)
        } else {
            setTextIntro(textIntroTemplate.substring(0, 300))
        }
    }

    return (
        <div className={styles.homeContainer}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

                <Navbar/>

            <main>

                <div className={styles.pgContainer}>
                    
                    <ParticlesBG />

                    <div className={styles.text}>

                        <h1>Je suis <a></a></h1>
                        <h2>Développeur Web Junior</h2>
                        <h3>Ceci est mon Portofolio!</h3>

                        <div className={styles.buttonContainer}>
                            <PurpleButton isPurple text="Mes projets"/>
                            <PurpleButton text="Télécharger CV" icon="fad fa-download" action={() => dlCV()}/>
                        </div>

                    </div>

                </div>

                <hr className={styles.separator1}/>

                <div style={{position: 'relative'}}>

                    <div className={styles.lineItem1}></div>
                    <div className={styles.lineItem2}></div>
                    <div className={styles.lineItem3}></div>
                    <div className={styles.lineItem4}></div>

                    <div className={styles.introContainer}>

                        <div className={styles.introBox}>

                            <div className={styles.reactTurn1}></div>
                            <div className={styles.reactTurn2}></div>
                            <div className={styles.reactTurn3}></div>
                            <div className={styles.reactTurn4}></div>

                            <div className={styles.profile}>
                                <img style={{backgroundImage: "url(https://cdn.discordapp.com/attachments/789414641498325032/920306693823430696/image0.png)"}}/>
                            
                                <div>
                                    <h1>Pornchai - C.</h1>
                                    <h2>Développeur Web</h2>
                                </div>

                            </div>


                            <div className={styles.introText}>
                                <h1>A propos de moi</h1>
                                <p>
                                    {textIntro}
                                    {textIntro !== textIntroTemplate ? 
                                        <button onClick={() => seeMore("plus")}>Voir plus</button> 
                                        : 
                                        <button onClick={() => seeMore("moins")}>Voir moins</button>
                                    }
                                </p>
                                <PurpleButton className={styles.infoBtn} text="Plus à propos de moi" icon="fad fa-hand-point-right"/>
                            </div>

                        </div>

                    </div>

                    <div className={styles.projectTitle}>
                        <h1>Mes projets</h1>

                        <div>
                            <Projects/>
                            <Projects/>
                            <Projects/>
                        </div>
                        <PurpleButton isPurple text="Voir plus de projet"/>
                    </div>

                </div>
                

            </main>

            <Footer/>

        </div>
        
    )
}
